#!/bin/bash
###########################################################
#                   Firewall
###########################################################

source /app/etc/fw/firewall.config

FWVER=20111106

save_dir=$2

###########################################################

start() {
    echo "Starting firewall..."
	${fwd}/firewall.flush
	${fwd}/firewall.police
	${fwd}/firewall.rules
}

stop() {
    echo "Stopping firewall..."
	${fwd}/firewall.flush
}

status() {
    echo
    echo "###############"
    echo "#Status FILTER#	FwVER: ${FWVER}"
    echo "###############"
    echo
	$IPTABLES -L -v -n --line-numbers
    echo
    echo "###############"
    echo "# Status  NAT #	FwVER: ${FWVER}"
    echo "###############"
    echo
	$IPTABLES -L -t nat -v -n --line-numbers
    echo
    echo "###############"
    echo "#Status MANGLE#	FwVER: ${FWVER}"
    echo "###############"
    echo
	$IPTABLES -L -t mangle -v -n --line-numbers
    echo
    echo "###############"
    echo "# Status  RAW #	FwVER: ${FWVER}"
    echo "###############"
    echo
	$IPTABLES -L -t raw -v -n --line-numbers
    echo
}

sourcee() {
    echo
    echo "###############"
    echo "#   Source    #	FwVER: ${FWVER}"
    echo "###############"
    echo
	$IPTABLES -S
    echo
}

gen_przeplyw() {
	for test in INPUT OUTPUT FORWARD POSTROUTING PREROUTING
	do
		iptables -S | grep $test > /app/etc/epp/all.$test
	done
}

wczyt_przeplyw() {
	rm /app/etc/fw/output.conf

	for test in INPUT OUTPUT FORWARD POSTROUTING PREROUTING
	do
		cat "/app/etc/epp/all.$test" >> /app/etc/fw/output.conf
	done
}


infobaner() {
    echo
    echo "################################################"
    echo "# FIREWALL: $0 ${FWSOURCE} FwVER:  ${FWVER} #"
    echo "################################################"
    echo
    echo "Options: {start|stop|reload|force-reload|restart|status|source|save|restore|rm-sv|przeplyw}"
    echo
    exit 1
}

############
### CASE ###
############

case "$1" in
  start)
    start
    ;;
  
  stop)
    stop
    ;;

  restart|reload|force-reload)
    start
    ;;

  status)
    status
    ;;
  source)

    sourcee
    ;;
  save)
    echo "Saving Firewall rules"
    echo "${FW_SAVE_DIR}/save_${2}"
    $iptsv > "${FW_SAVE_DIR}/save_${2}"
	if (($?==0)); then echo ok; else echo error; fi
    ;;
  restore)
    echo "Restoring Firewol rules from save"
    echo "${FW_SAVE_DIR}/save_${2}"
    $iptrs < "${FW_SAVE_DIR}/save_${2}" 
	if (($?==0)); then echo ok; else echo error; fi
    ;;
  rm-sv)
    rm ${FW_SAVE_DIR}/save_${2}
    ;;
  gen_przeplyw)
    gen_przeplyw
    ;;
  wczyt_przeplyw)
    wczyt_przeplyw
    $iptrs < "/app/etc/fw/output.conf"
    ;;
  *)
    infobaner

esac

exit 0
